apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-assesment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc
  template:
    metadata:
      labels:
        app: tc
    spec:
      containers:
      - name: tc-container
        image: andriisobchuk/march-test
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tc-service
spec:
  selector:
    app: tc
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

