apiVersion: apps/v1
kind: Deployment
metadata:
  name: march-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: march-test
  template:
    metadata:
      labels:
        app: march-test
    spec:
      containers:
      - name: march-test-container
        image: andriisobchuk/march-test
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: march-test-service
spec:
  selector:
    app: march-test
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

